# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
 
  exclude:
    # Archivos o directorios a excluir del análisis
    - build/**
    - "**/*.g.dart" # Archivos generados automáticamente

  strong-mode:
    implicit-casts: false # Evita conversiones implícitas de tipos.
    implicit-dynamic: false # Evita el uso implícito de `dynamic`.

linter:
  rules:
    # Reglas adicionales recomendadas
    - avoid_print # Evita usar `print`, usa un logger en su lugar.
    - prefer_const_constructors # Usa constructores const siempre que sea posible.
    - prefer_const_literals_to_create_immutables # Usa listas, mapas y conjuntos const.
    - avoid_unnecessary_containers # Evita usar contenedores innecesarios.
    - prefer_final_fields # Usa campos `final` cuando no cambian después de inicializarse.
    - avoid_empty_else # Evita bloques else vacíos.
    - prefer_is_not_empty # Usa `isNotEmpty` en lugar de `!isEmpty`.
    - prefer_single_quotes # Prefiere comillas simples para cadenas.
    - unnecessary_null_checks # Evita verificaciones nulas innecesarias.
    - use_key_in_widget_constructors # Asegúrate de que los widgets tienen un key en su constructor.
    - avoid_redundant_argument_values # Evita valores de argumento redundantes.


# Configuración para incluir la cobertura de análisis en más casos
monitored-variables:
  include:
    - unused_imports # Marca importaciones no usadas.
    - unused_local_variable # Marca variables locales no usadas.
